"""create core tables

Revision ID: 61580e624291
Revises: 
Create Date: 2025-11-11 11:15:03.732155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61580e624291'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'activities',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=120), nullable=False),
        sa.Column('parent_id', sa.Integer(), nullable=True),
        sa.Column('level', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['parent_id'], ['activities.id'], ondelete='CASCADE'),
        sa.CheckConstraint('level BETWEEN 1 AND 3', name='ck_activities_level_range'),
        sa.CheckConstraint(
            '(parent_id IS NULL AND level = 1) OR (parent_id IS NOT NULL AND level > 1)',
            name='ck_activities_level_parent',
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'buildings',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('city', sa.String(length=120), nullable=False),
        sa.Column('address', sa.String(length=255), nullable=False),
        sa.Column('latitude', sa.Float(), nullable=False),
        sa.Column('longitude', sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'organizations',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('building_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
    )
    op.create_table(
        'organization_activities',
        sa.Column('organization_id', sa.Integer(), nullable=False),
        sa.Column('activity_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('organization_id', 'activity_id'),
    )
    op.create_table(
        'organization_phones',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('organization_id', sa.Integer(), nullable=False),
        sa.Column('phone', sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('ix_activities_parent_id', 'activities', ['parent_id'])
    op.create_index('ix_activities_level', 'activities', ['level'])
    op.create_index('ix_buildings_latitude', 'buildings', ['latitude'])
    op.create_index('ix_buildings_longitude', 'buildings', ['longitude'])
    op.create_index('ix_organizations_building_id', 'organizations', ['building_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_organizations_building_id', table_name='organizations')
    op.drop_index('ix_buildings_longitude', table_name='buildings')
    op.drop_index('ix_buildings_latitude', table_name='buildings')
    op.drop_index('ix_activities_level', table_name='activities')
    op.drop_index('ix_activities_parent_id', table_name='activities')
    op.drop_table('organization_phones')
    op.drop_table('organization_activities')
    op.drop_table('organizations')
    op.drop_table('buildings')
    op.drop_table('activities')
    # ### end Alembic commands ###
